version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: micro_shop
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/logs:/logs
#      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - micro-shop